config/routes.rb
Rails.application.routes.draw do

  # For Home
  get '/', to: 'home#index', as: 'home'

  devise_for :users

  resources :links, only: [:index, :create]
  get '/l/:prefix', to: 'links#show', as: :short_link
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # Orders
  scope :newest_first, -> { order(created_at: :desc) }
  scope :oldest_first, -> { order(created_at: :asc) }
end

app/models/link.rb
class Link < ApplicationRecord
  # DB Relations
  belongs_to :user, optional: true

  # Validation
  validates :url, :prefix, presence: true
  validates :prefix, uniqueness: { case_sensitive: false }

  # Create uniq prefix
  def generate_prefix
    self.update(prefix: self.id.to_s + SecureRandom.hex(4))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # DB Relations
  has_many :links

  # Validation
  validates :password, :password_confirmation, presence: true, on: :create, length: { minimum: 6 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /index
  def index
    @link = Link.new
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET links/index
  def index
    # List all links
    @links = if current_user.present?
               current_user.links.newest_first.page(params[:page])
             else
               Link.newest_first.page(params[:page])
             end
  end

  # GET l/prefix
  def show
    link = Link.find_by(prefix: params[:prefix])
    if link.present?
      # Update visits
      link.update(visits: link.visits + 1)
      redirect_to link.url
    else
      render 'links/error', status: 404
    end
  end

  # POST links/create
  def create
    user = current_user.present? ? current_user.id : 0
    link = Link.new(link_params.merge(user_id: user, prefix: link_params[:url]))

    if link.save
      link.generate_prefix
      redirect_to home_path(link_prefix: link.prefix), notice: 'Link was successfully created.'
    else
      redirect_to home_path, flash: { error: 'Error in creation.' }
    end
  end

  private

  def link_params
    params.require(:link).permit(:user_id, :url, :prefix)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # For flash messages
  def bootstrap_class_for(flash_type)
    case flash_type
    when 'success'
      'alert-success' # Green
    when 'error'
      'alert-danger' # Red
    when 'alert'
      'alert-warning' # Yellow
    when 'notice'
      'alert-info' # Blue
    else
      Rails.logger.debug flash_type
    end
  end
end

app/views/home/index.html.erb
<%= render 'shared/navbar' %>

<%= form_for @link, url: url_for(controller: 'links', action: 'create'), :html => {method: :post} do |f| %>
  <!--row-->
  <div class="row">
    <!--form-group-->
    <div class="form-group col-lg-6">
      <%= f.label :url, class: 'form-label' %>
      <%= f.text_field :url, class: 'form-control', placeholder: 'https://example.com', required: true,
                             pattern: "[Hh][Tt][Tt][Pp][Ss]?:\/\/(?:(?:[a-zA-Z\u00a1-\uffff0-9]+-?)*[a-zA-Z\u00a1-\uffff0-9]+)(?:\.(?:[a-zA-Z\u00a1-\uffff0-9]+-?)*[a-zA-Z\u00a1-\uffff0-9]+)*(?:\.(?:[a-zA-Z\u00a1-\uffff]{2,}))(?::\d{2,5})?(?:\/[^\s]*)?" %>
    </div><!--form-group-->

    <!--row-->
    <div class="row">
      <!--form-group-->
      <div class="form-group col-lg-4">
        <label for="" style="color:#fff">.</label>
        <%= f.submit class: 'btn btn-primary' %>
      </div><!--form-group-->
    </div><!--row-->
  </div><!--row-->
<% end %>

<% if params[:link_prefix].present? %>
  <!--row-->
  <div class="row">
    <!--form-group-->
    <div class="form-group col-lg-6">
      <label for="short_link">Copy shot link:</label>
      <%= text_field_tag 'short_link', nil, class: 'form-control' , value: "#{ENV['App_Domain']}/l/#{params[:link_prefix]}" %>
    </div><!--form-group-->
  </div><!--row-->
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ENV['APP_Name'] %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<%= ENV['App_Description'] %>">
    <meta name="author" content="<%= ENV['App_Author'] %>">
    <!-- Favicon icon -->
    <link rel="icon" href="/favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--container-->
    <div class="container">
      <%= render partial: 'shared/alerts' %>

      <%= yield %>
    </div><!--container-->
  </body>
</html>

app/views/links/error.html.erb
<%= render 'shared/navbar' %>

<br>

error in short link

app/views/links/index.html.erb
<%= render 'shared/navbar' %>

<h4 class="card-title">
  Total links
  <small> <%=pluralize(@links.total_count, 'link')%> </small>
</h4>

<table class="tablesaw table-bordered table-hover table" data-tablesaw-mode="swipe" data-tablesaw-sortable data-tablesaw-sortable-switch data-tablesaw-minimap data-tablesaw-mode-switch>
  <thead>
    <tr>
      <th>User</th>
      <th>Url</th>
      <th>Short link</th>
      <th>Visits</th>
    </tr>
  </thead>
  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%=link&.user&.email%></td>
        <td>
          <%= link_to link.url, alt: link.url, title: link.url, target: '_blank'  do %><%= link.url %><% end %>
        </td>
        <td><%= link_to short_link_path(prefix: link.prefix), alt: link.url, title: link.url, target: '_blank'  do %>
          <%= ENV['App_Domain'] %>/l/<%= link.prefix %>
          <% end %>
        </td>
        <td><%= link.visits %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<nav aria-label="Page navigation">
  <%= paginate @links %>
</nav>

app/views/shared/_alerts.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true" aria-label="Close">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-center">
  <%= link_to 'ShortLinks App', home_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'New link', home_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'My links', links_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<br><br>